version: '2'
services:
    notification-app:
        image: notification
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://notification-mysql:3306/notification?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    notification-mysql:
        extends:
            file: mysql.yml
            service: notification-mysql
